apiVersion: v1
kind: Service
metadata:
  name: kube-react-app
  labels:
    app: kube-react-app
spec:
  type: LoadBalancer
  selector:
    app: kube-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
